language: node_js
node_js:
- 12.13.1
cache: npm

install:
- yarn install

script:
- yarn run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN 
  local_dir: build
  on:
    branch: master
